# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqJYvdqPYpgiApvrmd2NHNPQPkflfpwm
"""

# prompt: Grafica de amplitud modulada

import numpy as np
import matplotlib.pyplot as plt

# Parámetros de la señal portadora
fc = 10  # Frecuencia de la portadora (Hz)
Ac = 1   # Amplitud de la portadora

# Parámetros de la señal moduladora
fm = 1   # Frecuencia de la moduladora (Hz)
Am = 0.5 # Amplitud de la moduladora

# Tiempo
t = np.linspace(0, 1, 500)  # Vector de tiempo de 0 a 1 segundo con 500 puntos

# Señal portadora
carrier = Ac * np.cos(2 * np.pi * fc * t)

# Señal moduladora
modulator = Am * np.cos(2 * np.pi * fm * t)

# Señal modulada en amplitud (AM)
modulated_signal = Ac * (1 + modulator) * np.cos(2 * np.pi * fc * t)


# Graficar las señales
plt.figure(figsize=(12, 8))

plt.subplot(3, 1, 1)
plt.plot(t, carrier)
plt.title('Señal Portadora')
plt.xlabel('Tiempo (s)')
plt.ylabel('Amplitud')


plt.subplot(3, 1, 2)
plt.plot(t, modulator)
plt.title('Señal Moduladora')
plt.xlabel('Tiempo (s)')
plt.ylabel('Amplitud')


plt.subplot(3, 1, 3)
plt.plot(t, modulated_signal)
plt.title('Señal Modulada en Amplitud (AM)')
plt.xlabel('Tiempo (s)')
plt.ylabel('Amplitud')

plt.tight_layout() # Ajusta el espacio entre subplots
plt.show()